#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyBenXe")]
	public partial class QLBXDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertNhomNguoiDung(NhomNguoiDung instance);
    partial void UpdateNhomNguoiDung(NhomNguoiDung instance);
    partial void DeleteNhomNguoiDung(NhomNguoiDung instance);
    partial void InsertPhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void UpdatePhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void DeletePhanQuyenNguoiDung(PhanQuyenNguoiDung instance);
    partial void InsertPhanQuyenNhom(PhanQuyenNhom instance);
    partial void UpdatePhanQuyenNhom(PhanQuyenNhom instance);
    partial void DeletePhanQuyenNhom(PhanQuyenNhom instance);
    partial void InsertManHinh(ManHinh instance);
    partial void UpdateManHinh(ManHinh instance);
    partial void DeleteManHinh(ManHinh instance);
    #endregion
		
		public QLBXDataContext() : 
				base(global::DAO.Properties.Settings.Default.QuanLyBenXeConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLBXDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBXDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBXDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLBXDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<NhomNguoiDung> NhomNguoiDungs
		{
			get
			{
				return this.GetTable<NhomNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this.GetTable<PhanQuyenNguoiDung>();
			}
		}
		
		public System.Data.Linq.Table<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this.GetTable<PhanQuyenNhom>();
			}
		}
		
		public System.Data.Linq.Table<ManHinh> ManHinhs
		{
			get
			{
				return this.GetTable<ManHinh>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_delete_PhanQuyenNguoiDung")]
		public int pro_delete_PhanQuyenNguoiDung([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhanVien", DbType="Int")] System.Nullable<int> idNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhomNguoiDung", DbType="Int")] System.Nullable<int> idNhomNguoiDung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNhanVien, idNhomNguoiDung);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_delete_PhanQuyenNhom")]
		public int pro_delete_PhanQuyenNhom([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> id_nhom_nguoi_dung_del)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_nhom_nguoi_dung_del);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_KiemTraDangNhap")]
		public ISingleResult<pro_KiemTraDangNhapResult> pro_KiemTraDangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="VarChar(100)")] string taiKhoan, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MatKhau", DbType="VarChar(100)")] string matKhau)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan, matKhau);
			return ((ISingleResult<pro_KiemTraDangNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_KiemTraHoatDong")]
		public ISingleResult<pro_KiemTraHoatDongResult> pro_KiemTraHoatDong([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="VarChar(100)")] string taiKhoan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan);
			return ((ISingleResult<pro_KiemTraHoatDongResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_KiemTraQuyen")]
		public ISingleResult<pro_KiemTraQuyenResult> pro_KiemTraQuyen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TaiKhoan", DbType="VarChar(100)")] string taiKhoan)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), taiKhoan);
			return ((ISingleResult<pro_KiemTraQuyenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_show_DanhSachNguoiDung_DK")]
		public ISingleResult<NhanVien> pro_show_DanhSachNguoiDung_DK([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhom", DbType="Int")] System.Nullable<int> idNhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNhom);
			return ((ISingleResult<NhanVien>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_show_DanhSachNguoiDung_TheoNhom")]
		public ISingleResult<NhanVien> pro_show_DanhSachNguoiDung_TheoNhom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhom", DbType="Int")] System.Nullable<int> idNhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNhom);
			return ((ISingleResult<NhanVien>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_show_PhanQuyen")]
		public ISingleResult<pro_show_PhanQuyenResult> pro_show_PhanQuyen([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhom", DbType="Int")] System.Nullable<int> idNhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNhom);
			return ((ISingleResult<pro_show_PhanQuyenResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_ThemPhanQuyenNhom")]
		public int pro_ThemPhanQuyenNhom([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Id_nhom", DbType="Int")] System.Nullable<int> id_nhom)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), id_nhom);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.pro_insert_PhanQuyenNguoiung")]
		public int pro_insert_PhanQuyenNguoiung([global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhanVien", DbType="Int")] System.Nullable<int> idNhanVien, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IdNhomNguoiDung", DbType="Int")] System.Nullable<int> idNhomNguoiDung)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idNhanVien, idNhomNguoiDung);
			return ((int)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhan_vien;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _HoatDong;
		
		private EntitySet<PhanQuyenNguoiDung> _PhanQuyenNguoiDungs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhan_vienChanging(int value);
    partial void Onid_nhan_vienChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnHoatDongChanging(System.Nullable<bool> value);
    partial void OnHoatDongChanged();
    #endregion
		
		public NhanVien()
		{
			this._PhanQuyenNguoiDungs = new EntitySet<PhanQuyenNguoiDung>(new Action<PhanQuyenNguoiDung>(this.attach_PhanQuyenNguoiDungs), new Action<PhanQuyenNguoiDung>(this.detach_PhanQuyenNguoiDungs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="Bit")]
		public System.Nullable<bool> HoatDong
		{
			get
			{
				return this._HoatDong;
			}
			set
			{
				if ((this._HoatDong != value))
				{
					this.OnHoatDongChanging(value);
					this.SendPropertyChanging();
					this._HoatDong = value;
					this.SendPropertyChanged("HoatDong");
					this.OnHoatDongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanQuyenNguoiDung", Storage="_PhanQuyenNguoiDungs", ThisKey="id_nhan_vien", OtherKey="id_nhan_vien")]
		public EntitySet<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this._PhanQuyenNguoiDungs;
			}
			set
			{
				this._PhanQuyenNguoiDungs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = this;
		}
		
		private void detach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhomNguoiDung")]
	public partial class NhomNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhom_nguoi_dung;
		
		private string _ten_nhom_nguoi_dung;
		
		private EntitySet<PhanQuyenNguoiDung> _PhanQuyenNguoiDungs;
		
		private EntitySet<PhanQuyenNhom> _PhanQuyenNhoms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhom_nguoi_dungChanging(int value);
    partial void Onid_nhom_nguoi_dungChanged();
    partial void Onten_nhom_nguoi_dungChanging(string value);
    partial void Onten_nhom_nguoi_dungChanged();
    #endregion
		
		public NhomNguoiDung()
		{
			this._PhanQuyenNguoiDungs = new EntitySet<PhanQuyenNguoiDung>(new Action<PhanQuyenNguoiDung>(this.attach_PhanQuyenNguoiDungs), new Action<PhanQuyenNguoiDung>(this.detach_PhanQuyenNguoiDungs));
			this._PhanQuyenNhoms = new EntitySet<PhanQuyenNhom>(new Action<PhanQuyenNhom>(this.attach_PhanQuyenNhoms), new Action<PhanQuyenNhom>(this.detach_PhanQuyenNhoms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhom_nguoi_dung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_nhom_nguoi_dung
		{
			get
			{
				return this._id_nhom_nguoi_dung;
			}
			set
			{
				if ((this._id_nhom_nguoi_dung != value))
				{
					this.Onid_nhom_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._id_nhom_nguoi_dung = value;
					this.SendPropertyChanged("id_nhom_nguoi_dung");
					this.Onid_nhom_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhom_nguoi_dung", DbType="NVarChar(100)")]
		public string ten_nhom_nguoi_dung
		{
			get
			{
				return this._ten_nhom_nguoi_dung;
			}
			set
			{
				if ((this._ten_nhom_nguoi_dung != value))
				{
					this.Onten_nhom_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._ten_nhom_nguoi_dung = value;
					this.SendPropertyChanged("ten_nhom_nguoi_dung");
					this.Onten_nhom_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyenNguoiDung", Storage="_PhanQuyenNguoiDungs", ThisKey="id_nhom_nguoi_dung", OtherKey="id_nhom_nguoi_dung")]
		public EntitySet<PhanQuyenNguoiDung> PhanQuyenNguoiDungs
		{
			get
			{
				return this._PhanQuyenNguoiDungs;
			}
			set
			{
				this._PhanQuyenNguoiDungs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyenNhom", Storage="_PhanQuyenNhoms", ThisKey="id_nhom_nguoi_dung", OtherKey="id_nhom_nguoi_dung")]
		public EntitySet<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this._PhanQuyenNhoms;
			}
			set
			{
				this._PhanQuyenNhoms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = this;
		}
		
		private void detach_PhanQuyenNguoiDungs(PhanQuyenNguoiDung entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = null;
		}
		
		private void attach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = this;
		}
		
		private void detach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.NhomNguoiDung = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyenNguoiDung")]
	public partial class PhanQuyenNguoiDung : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhan_vien;
		
		private int _id_nhom_nguoi_dung;
		
		private EntityRef<NhanVien> _NhanVien;
		
		private EntityRef<NhomNguoiDung> _NhomNguoiDung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhan_vienChanging(int value);
    partial void Onid_nhan_vienChanged();
    partial void Onid_nhom_nguoi_dungChanging(int value);
    partial void Onid_nhom_nguoi_dungChanged();
    #endregion
		
		public PhanQuyenNguoiDung()
		{
			this._NhanVien = default(EntityRef<NhanVien>);
			this._NhomNguoiDung = default(EntityRef<NhomNguoiDung>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					if (this._NhanVien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhan_vienChanging(value);
					this.SendPropertyChanging();
					this._id_nhan_vien = value;
					this.SendPropertyChanged("id_nhan_vien");
					this.Onid_nhan_vienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhom_nguoi_dung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nhom_nguoi_dung
		{
			get
			{
				return this._id_nhom_nguoi_dung;
			}
			set
			{
				if ((this._id_nhom_nguoi_dung != value))
				{
					if (this._NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhom_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._id_nhom_nguoi_dung = value;
					this.SendPropertyChanged("id_nhom_nguoi_dung");
					this.Onid_nhom_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_PhanQuyenNguoiDung", Storage="_NhanVien", ThisKey="id_nhan_vien", OtherKey="id_nhan_vien", IsForeignKey=true)]
		public NhanVien NhanVien
		{
			get
			{
				return this._NhanVien.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien.Entity = null;
						previousValue.PhanQuyenNguoiDungs.Remove(this);
					}
					this._NhanVien.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNguoiDungs.Add(this);
						this._id_nhan_vien = value.id_nhan_vien;
					}
					else
					{
						this._id_nhan_vien = default(int);
					}
					this.SendPropertyChanged("NhanVien");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyenNguoiDung", Storage="_NhomNguoiDung", ThisKey="id_nhom_nguoi_dung", OtherKey="id_nhom_nguoi_dung", IsForeignKey=true)]
		public NhomNguoiDung NhomNguoiDung
		{
			get
			{
				return this._NhomNguoiDung.Entity;
			}
			set
			{
				NhomNguoiDung previousValue = this._NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNguoiDung.Entity = null;
						previousValue.PhanQuyenNguoiDungs.Remove(this);
					}
					this._NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNguoiDungs.Add(this);
						this._id_nhom_nguoi_dung = value.id_nhom_nguoi_dung;
					}
					else
					{
						this._id_nhom_nguoi_dung = default(int);
					}
					this.SendPropertyChanged("NhomNguoiDung");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhanQuyenNhom")]
	public partial class PhanQuyenNhom : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_nhom_nguoi_dung;
		
		private int _id_man_hinh;
		
		private System.Nullable<bool> _quyen;
		
		private EntityRef<NhomNguoiDung> _NhomNguoiDung;
		
		private EntityRef<ManHinh> _ManHinh;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_nhom_nguoi_dungChanging(int value);
    partial void Onid_nhom_nguoi_dungChanged();
    partial void Onid_man_hinhChanging(int value);
    partial void Onid_man_hinhChanged();
    partial void OnquyenChanging(System.Nullable<bool> value);
    partial void OnquyenChanged();
    #endregion
		
		public PhanQuyenNhom()
		{
			this._NhomNguoiDung = default(EntityRef<NhomNguoiDung>);
			this._ManHinh = default(EntityRef<ManHinh>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhom_nguoi_dung", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_nhom_nguoi_dung
		{
			get
			{
				return this._id_nhom_nguoi_dung;
			}
			set
			{
				if ((this._id_nhom_nguoi_dung != value))
				{
					if (this._NhomNguoiDung.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_nhom_nguoi_dungChanging(value);
					this.SendPropertyChanging();
					this._id_nhom_nguoi_dung = value;
					this.SendPropertyChanged("id_nhom_nguoi_dung");
					this.Onid_nhom_nguoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_man_hinh", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id_man_hinh
		{
			get
			{
				return this._id_man_hinh;
			}
			set
			{
				if ((this._id_man_hinh != value))
				{
					if (this._ManHinh.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onid_man_hinhChanging(value);
					this.SendPropertyChanging();
					this._id_man_hinh = value;
					this.SendPropertyChanged("id_man_hinh");
					this.Onid_man_hinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Bit")]
		public System.Nullable<bool> quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhomNguoiDung_PhanQuyenNhom", Storage="_NhomNguoiDung", ThisKey="id_nhom_nguoi_dung", OtherKey="id_nhom_nguoi_dung", IsForeignKey=true)]
		public NhomNguoiDung NhomNguoiDung
		{
			get
			{
				return this._NhomNguoiDung.Entity;
			}
			set
			{
				NhomNguoiDung previousValue = this._NhomNguoiDung.Entity;
				if (((previousValue != value) 
							|| (this._NhomNguoiDung.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhomNguoiDung.Entity = null;
						previousValue.PhanQuyenNhoms.Remove(this);
					}
					this._NhomNguoiDung.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNhoms.Add(this);
						this._id_nhom_nguoi_dung = value.id_nhom_nguoi_dung;
					}
					else
					{
						this._id_nhom_nguoi_dung = default(int);
					}
					this.SendPropertyChanged("NhomNguoiDung");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyenNhom", Storage="_ManHinh", ThisKey="id_man_hinh", OtherKey="id_man_hinh", IsForeignKey=true)]
		public ManHinh ManHinh
		{
			get
			{
				return this._ManHinh.Entity;
			}
			set
			{
				ManHinh previousValue = this._ManHinh.Entity;
				if (((previousValue != value) 
							|| (this._ManHinh.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ManHinh.Entity = null;
						previousValue.PhanQuyenNhoms.Remove(this);
					}
					this._ManHinh.Entity = value;
					if ((value != null))
					{
						value.PhanQuyenNhoms.Add(this);
						this._id_man_hinh = value.id_man_hinh;
					}
					else
					{
						this._id_man_hinh = default(int);
					}
					this.SendPropertyChanged("ManHinh");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ManHinh")]
	public partial class ManHinh : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id_man_hinh;
		
		private string _ten_man_hinh;
		
		private EntitySet<PhanQuyenNhom> _PhanQuyenNhoms;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onid_man_hinhChanging(int value);
    partial void Onid_man_hinhChanged();
    partial void Onten_man_hinhChanging(string value);
    partial void Onten_man_hinhChanged();
    #endregion
		
		public ManHinh()
		{
			this._PhanQuyenNhoms = new EntitySet<PhanQuyenNhom>(new Action<PhanQuyenNhom>(this.attach_PhanQuyenNhoms), new Action<PhanQuyenNhom>(this.detach_PhanQuyenNhoms));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_man_hinh", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id_man_hinh
		{
			get
			{
				return this._id_man_hinh;
			}
			set
			{
				if ((this._id_man_hinh != value))
				{
					this.Onid_man_hinhChanging(value);
					this.SendPropertyChanging();
					this._id_man_hinh = value;
					this.SendPropertyChanged("id_man_hinh");
					this.Onid_man_hinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_man_hinh", DbType="NVarChar(100)")]
		public string ten_man_hinh
		{
			get
			{
				return this._ten_man_hinh;
			}
			set
			{
				if ((this._ten_man_hinh != value))
				{
					this.Onten_man_hinhChanging(value);
					this.SendPropertyChanging();
					this._ten_man_hinh = value;
					this.SendPropertyChanged("ten_man_hinh");
					this.Onten_man_hinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ManHinh_PhanQuyenNhom", Storage="_PhanQuyenNhoms", ThisKey="id_man_hinh", OtherKey="id_man_hinh")]
		public EntitySet<PhanQuyenNhom> PhanQuyenNhoms
		{
			get
			{
				return this._PhanQuyenNhoms;
			}
			set
			{
				this._PhanQuyenNhoms.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = this;
		}
		
		private void detach_PhanQuyenNhoms(PhanQuyenNhom entity)
		{
			this.SendPropertyChanging();
			entity.ManHinh = null;
		}
	}
	
	public partial class pro_KiemTraDangNhapResult
	{
		
		private int _id_nhan_vien;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _HoatDong;
		
		public pro_KiemTraDangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="Int NOT NULL")]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					this._id_nhan_vien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this._TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="Bit")]
		public System.Nullable<bool> HoatDong
		{
			get
			{
				return this._HoatDong;
			}
			set
			{
				if ((this._HoatDong != value))
				{
					this._HoatDong = value;
				}
			}
		}
	}
	
	public partial class pro_KiemTraHoatDongResult
	{
		
		private int _id_nhan_vien;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private System.Nullable<bool> _HoatDong;
		
		public pro_KiemTraHoatDongResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhan_vien", DbType="Int NOT NULL")]
		public int id_nhan_vien
		{
			get
			{
				return this._id_nhan_vien;
			}
			set
			{
				if ((this._id_nhan_vien != value))
				{
					this._id_nhan_vien = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this._TaiKhoan = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this._MatKhau = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoatDong", DbType="Bit")]
		public System.Nullable<bool> HoatDong
		{
			get
			{
				return this._HoatDong;
			}
			set
			{
				if ((this._HoatDong != value))
				{
					this._HoatDong = value;
				}
			}
		}
	}
	
	public partial class pro_KiemTraQuyenResult
	{
		
		private int _id_man_hinh;
		
		public pro_KiemTraQuyenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_man_hinh", DbType="Int NOT NULL")]
		public int id_man_hinh
		{
			get
			{
				return this._id_man_hinh;
			}
			set
			{
				if ((this._id_man_hinh != value))
				{
					this._id_man_hinh = value;
				}
			}
		}
	}
	
	public partial class pro_show_PhanQuyenResult
	{
		
		private int _id_nhom_nguoi_dung;
		
		private string _ten_nhom_nguoi_dung;
		
		private int _id_man_hinh;
		
		private string _ten_man_hinh;
		
		private System.Nullable<bool> _quyen;
		
		public pro_show_PhanQuyenResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_nhom_nguoi_dung", DbType="Int NOT NULL")]
		public int id_nhom_nguoi_dung
		{
			get
			{
				return this._id_nhom_nguoi_dung;
			}
			set
			{
				if ((this._id_nhom_nguoi_dung != value))
				{
					this._id_nhom_nguoi_dung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_nhom_nguoi_dung", DbType="NVarChar(100)")]
		public string ten_nhom_nguoi_dung
		{
			get
			{
				return this._ten_nhom_nguoi_dung;
			}
			set
			{
				if ((this._ten_nhom_nguoi_dung != value))
				{
					this._ten_nhom_nguoi_dung = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id_man_hinh", DbType="Int NOT NULL")]
		public int id_man_hinh
		{
			get
			{
				return this._id_man_hinh;
			}
			set
			{
				if ((this._id_man_hinh != value))
				{
					this._id_man_hinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_man_hinh", DbType="NVarChar(100)")]
		public string ten_man_hinh
		{
			get
			{
				return this._ten_man_hinh;
			}
			set
			{
				if ((this._ten_man_hinh != value))
				{
					this._ten_man_hinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="Bit")]
		public System.Nullable<bool> quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this._quyen = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
